TYPE_X(NULL)		// the None / null type
TYPE_X(ERROR)		// Error / exception
TYPE_X(SYMBOL)		// BearLang symbol
TYPE_X(NUMBER)		// Numeric value
TYPE_X(BOOL)		// Boolean value
TYPE_X(STRING)		// String
TYPE_X(CONS)		// Cons cell or list
TYPE_X(OPER_NATIVE)	// native-code oper
TYPE_X(FUNC_NATIVE)	// native-code func
TYPE_X(OPER_BL)		// oper implemented in BearLang code
TYPE_X(FUNC_BL)		// function implemented in BearLang code
TYPE_X(CTX)		// context / environment
TYPE_X(CPTR)		// C pointer, used by extension modules
TYPE_X(ANY)		// matches any type, used for error handling etc
TYPE_X(LIST_END)	// used by parser
TYPE_X(OPER_DO)		// special form - the do oper
TYPE_X(OPER_IF)		// special form - the if oper
TYPE_X(OPER_WHILE)	// special form - the while oper
TYPE_X(DOCSTRING)	// documentation string (docstr)
TYPE_X(TYPE)		// reference to a type
